### ISSUE TITLE
Deploy.

### ISSUE THREAD

**Issue by fvieir** [Carlos-Moraes2/Tip-Calculator#2]
Fala Carlos, como vai?

Conforme deixado o Feedback e orientações no Discord, segue minhas solicitação para entrega do deploy.

Para deploy você pode usar o netlify, mas sinta-se livre para usar outras plataformas.

Qualquer duvida é so chamar.

Forte abraço.

**Comment by Carlos-Moraes2** [comment]
Fala Fabricio tudo bem, obrigado por suas orientações acabei de fazer o deploy do meu projeto aqui.

**Comment by carlosmoraes-dev** [comment]
Tudo bem e você Fabricio? fiz como o deploy como sugerido muito obrigado pelo feedback.
